<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Aceh Gayo Enzymatic Civet-Free',
                'name_id' => 'Aceh Gayo Luwak Enzimatik Bebas Eksploitasi',
                'slug' => 'aceh-gayo-enzymatic',
                'category' => 'arabika',
                'description' => 'Flagship single-origin Arabica from Takengon highlands processed with proprietary enzymatic bio-fermentation. Ultra-low bitterness, velvety mouthfeel with notes of dark chocolate, wild berries, and brown sugar.',
                'description_id' => 'Arabika single-origin unggulan dari dataran tinggi Takengon yang diproses dengan bio-fermentasi enzimatik proprietary. Rasa pahit sangat rendah, tekstur lembut velvety dengan aroma cokelat pekat, beri liar, dan gula aren.',
                'origin' => 'Aceh Gayo (1,400 - 1,700 MASL)',
                'altitude' => '1400 - 1700m',
                'process' => 'Enzymatic Bio-Fermentation',
                'roast_level' => 'medium',
                'sca_score' => '87.5',
                'tasting_notes' => ['Dark Chocolate', 'Wild Berry', 'Brown Sugar', 'Velvety Body'],
                'flavor_tags' => ['Fruity', 'Sweet', 'Smooth'],
                'recommended_brews' => ['v60', 'espresso', 'french_press'],
                'image' => 'https://images.unsplash.com/photo-1587734195503-904fca47e0e9?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 95000,
                'price_500g' => 220000,
                'price_1kg' => 410000,
                'stock' => 50,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Toraja Sapan Specialty Natural',
                'name_id' => 'Toraja Sapan Spesialti Natural',
                'slug' => 'toraja-sapan-specialty-natural',
                'category' => 'arabika',
                'description' => 'Grown in the mystical peaks of North Toraja. Slowly sun-dried in whole cherry to develop intense sweetness, tropical fruit brightness, red apple acidity, and a lingering floral finish.',
                'description_id' => 'Ditanam di lereng pegunungan Toraja Utara. Dijemur perlahan dalam ceri utuh untuk menghasilkan rasa manis pekat, kecerahan buah tropis, keasaman apel merah, dan aftertaste bunga yang tahan lama.',
                'origin' => 'Toraja Sapan (1,700 - 2,100 MASL)',
                'altitude' => '1700 - 2100m',
                'process' => 'Natural Sun-Dried',
                'roast_level' => 'light',
                'sca_score' => '86.5',
                'tasting_notes' => ['Red Apple', 'Tropical Mango', 'Jasmine', 'Honey Sweetness'],
                'flavor_tags' => ['Fruity', 'Floral', 'Bright'],
                'recommended_brews' => ['v60', 'cold_brew'],
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 88000,
                'price_500g' => 205000,
                'price_1kg' => 380000,
                'stock' => 40,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'West Java Preanger Anaerobic Honey',
                'name_id' => 'Jawa Barat Preanger Anaerobik Madu',
                'slug' => 'west-java-preanger-anaerobic-honey',
                'category' => 'arabika',
                'description' => 'Classic historic Preanger heirloom beans subject to a 72-hour anaerobic fermentation before honey drying. Complex stone fruit acidity with layered caramel and silky honey mouthfeel.',
                'description_id' => 'Biji kopi varietas legendaris Priangan Jawa Barat melalui fermentasi anaerobik 72 jam sebelum penjemuran madu. Karakter buah persik dengan lapisan karamel dan tekstur madu yang sangat halus.',
                'origin' => 'Ciwidey, West Java (1,500 - 1,650 MASL)',
                'altitude' => '1500 - 1650m',
                'process' => 'Anaerobic Honey',
                'roast_level' => 'medium',
                'sca_score' => '85.5',
                'tasting_notes' => ['Peach', 'Orange Marmalade', 'Caramel', 'Silky Honey'],
                'flavor_tags' => ['Sweet', 'Fruity', 'Balanced'],
                'recommended_brews' => ['v60', 'espresso', 'french_press'],
                'image' => 'https://images.unsplash.com/photo-1611854779393-1b2da9d400fe?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 82000,
                'price_500g' => 190000,
                'price_1kg' => 350000,
                'stock' => 60,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Temanggung Fine Robusta Wine Process',
                'name_id' => 'Temanggung Fine Robusta Proses Wine',
                'slug' => 'temanggung-fine-robusta-wine',
                'category' => 'robusta',
                'description' => 'Specialty grade fine Robusta grown on the slopes of Mount Sindoro. Prolonged extended natural fermentation yields rich dark cacao, black grape, fermented plum, and heavy syrupy crema.',
                'description_id' => 'Robusta kualitas tinggi dari lereng Gunung Sindoro. Fermentasi natural panjang menghadirkan nuansa kakao pekat, anggur hitam, prem fermentasi, dan krema tebal legit.',
                'origin' => 'Temanggung, Central Java (800 - 1,000 MASL)',
                'altitude' => '800 - 1000m',
                'process' => 'Extended Natural Wine',
                'roast_level' => 'medium_dark',
                'sca_score' => '83.0',
                'tasting_notes' => ['Dark Cocoa', 'Blackcurrant', 'Fermented Plum', 'Heavy Crema'],
                'flavor_tags' => ['Bold', 'Chocolatey', 'Winey'],
                'recommended_brews' => ['espresso', 'tubruk', 'cold_brew'],
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 65000,
                'price_500g' => 150000,
                'price_1kg' => 280000,
                'stock' => 75,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Dampit Malang Highland Robusta High Roast',
                'name_id' => 'Robusta Dataran Tinggi Dampit Malang Roasting Pekat',
                'slug' => 'dampit-malang-high-roast',
                'category' => 'robusta',
                'description' => 'World-famous East Java Robusta cultivated in volcanic soil. Roasted dark for dense earthy cedar, roasted hazelnut, dark caramel, and exceptional body that cuts through milk brilliantly.',
                'description_id' => 'Robusta Dampit tersohor dari Jawa Timur dengan tanah vulkanik subur. Di-roast gelap untuk karakter kayu cedar, hazelnut panggang, karamel gelap, dan bodi tebal mantap untuk kopi susu.',
                'origin' => 'Dampit, Malang (700 - 900 MASL)',
                'altitude' => '700 - 900m',
                'process' => 'Washed Polished',
                'roast_level' => 'dark',
                'sca_score' => '82.0',
                'tasting_notes' => ['Roasted Hazelnut', 'Cedar Wood', 'Dark Molasses', 'Heavy Body'],
                'flavor_tags' => ['Bold', 'Nutty', 'Smoky'],
                'recommended_brews' => ['espresso', 'tubruk', 'french_press'],
                'image' => 'https://images.unsplash.com/photo-1498804103079-a6351b050096?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 58000,
                'price_500g' => 135000,
                'price_1kg' => 250000,
                'stock' => 100,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'name' => 'Lima Biji Signature House Blend (70/30)',
                'name_id' => 'House Blend Signature Lima Biji (70/30)',
                'slug' => 'lima-biji-signature-house-blend',
                'category' => 'blend',
                'description' => 'Our master roaster signature formulation: 70% Enzymatic Gayo Arabica married with 30% Temanggung Fine Robusta. Incredibly sweet espresso, thick golden tiger crema, and luscious milk-drink sweetness.',
                'description_id' => 'Formula racikan khas master roaster kami: 70% Arabika Gayo Enzimatik berpadu dengan 30% Fine Robusta Temanggung. Espresso manis legit, krema emas harimau tebal, dan sempurna untuk racikan kopi susu.',
                'origin' => 'Aceh Gayo + Temanggung Highlands',
                'altitude' => '1000 - 1600m',
                'process' => 'Enzymatic & Honey Blend',
                'roast_level' => 'medium_dark',
                'sca_score' => '85.0',
                'tasting_notes' => ['Milk Chocolate', 'Toasted Almond', 'Vanilla Cream', 'Brown Sugar'],
                'flavor_tags' => ['Chocolatey', 'Nutty', 'Sweet'],
                'recommended_brews' => ['espresso', 'tubruk', 'french_press', 'cold_brew'],
                'image' => 'https://images.unsplash.com/photo-1518832553480-cd0e625ed3e6?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 78000,
                'price_500g' => 180000,
                'price_1kg' => 330000,
                'stock' => 85,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Tropical Yeast Anaerobic Fermentation #05',
                'name_id' => 'Fermentasi Ragi Tropis Anaerobik #05',
                'slug' => 'tropical-yeast-anaerobic-05',
                'category' => 'experimental',
                'description' => 'Experimental micro-lot using cultured Saccharomyces yeast strains and fruit-infused anaerobic tanks. Exploding with passion fruit candy, guava, sparkling lime acidity, and botanical lavender notes.',
                'description_id' => 'Micro-lot eksperimental menggunakan ragi Saccharomyces terkontrol dalam tangki fermentasi anaerobik bertekanan. Ledakan rasa markisa, jambu biji merah, keasaman jeruk nipis segar, dan lavender aromatik.',
                'origin' => 'Mount Papandayan, Garut (1,600 MASL)',
                'altitude' => '1600m',
                'process' => 'Cultured Yeast Inoculation',
                'roast_level' => 'light',
                'sca_score' => '88.5',
                'tasting_notes' => ['Passion Fruit', 'Pink Guava', 'Sparkling Lime', 'Lavender Tea'],
                'flavor_tags' => ['Fruity', 'Experimental', 'Floral'],
                'recommended_brews' => ['v60', 'cold_brew'],
                'image' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 110000,
                'price_500g' => 255000,
                'price_1kg' => 480000,
                'stock' => 25,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'name' => 'Bali Kintamani Citrus Carbonic Maceration',
                'name_id' => 'Bali Kintamani Karbonik Maserasi Jeruk',
                'slug' => 'bali-kintamani-carbonic-maceration',
                'category' => 'experimental',
                'description' => 'Shade-grown amidst orange groves on Mount Batur caldera. Sealed in pressurized CO2 tanks for 100 hours. Vibrantly juicy with sweet tangerine, dried apricot, lemongrass, and honey jasmine finish.',
                'description_id' => 'Tumbuh di bawah naungan kebun jeruk keprok lereng kaldera Gunung Batur. Difermentasi dalam tangki bertekanan gas CO2 selama 100 jam. Rasa segar jeruk manis, aprikot kering, serai wangi, dan melati madu.',
                'origin' => 'Kintamani, Bali (1,300 - 1,500 MASL)',
                'altitude' => '1300 - 1500m',
                'process' => 'Carbonic Maceration 100h',
                'roast_level' => 'medium',
                'sca_score' => '87.0',
                'tasting_notes' => ['Sweet Tangerine', 'Dried Apricot', 'Lemongrass', 'Honey Jasmine'],
                'flavor_tags' => ['Fruity', 'Citrus', 'Sweet'],
                'recommended_brews' => ['v60', 'cold_brew', 'espresso'],
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?q=80&w=800&auto=format&fit=crop',
                'base_price_200g' => 105000,
                'price_500g' => 245000,
                'price_1kg' => 460000,
                'stock' => 30,
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($products as $item) {
            Product::updateOrCreate(['slug' => $item['slug']], $item);
        }
    }
}
